- hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
     path: "/home/{{filename}}"
     state: touch
     tags:
     - always

- hosts: all
  tasks:     
   - name: Ansible create file if it doesn't exist example in tmp folder  
    file:
     path: "/tmp/{{filename}}"
     state: touch
     tags:
     - tmp
