- hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
     path: "/home/{{filename}}"
     state: touch
    tags:
    - tag1

  - name: Ansible create file with content example
    copy:
      dest: "/home/{{filename}}"
      content: |
        dog1
        tiger
      
    tags:
        - tag2
