- hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
     path: "/home/{{filename}}"
     state: touch
    tags:
    - tag1

  - name: Ansible create file with content example
    copy:
      dest: "/home/{{filename}}"
      content: |
        dog1
        tiger
      
    tags:
    - tag2
    
  - name: Ansible create file with content2
    copy:
      dest: "/home/{{filename}}"
      content: |
        tam
        jam
      
    tags:
    - tag3
    
  - name: Ansible create file with content3
    copy:
      dest: "/home/{{filename}}"
      content: |
        bird
        bird1
      
    tags:
    - tag4    
